#!/usr/bin/env python3
"""
Fast-path training submission for environments already on the Prime Hub.

NOTE: Both HF datasets and Prime environments use owner/name format.
Confirm it's a Prime environment first: prime env info owner/name (exit 0 = Prime env)

Usage:
  python scripts/submit_training.py --env owner/env-name
  python scripts/submit_training.py --env owner/env-name --model Qwen/Qwen3-4B-Instruct-2507 --yes

Options:
  --env       Hub environment ID (required), e.g. zain/gsm8k-env
  --model     Model to train (default: Qwen/Qwen3-4B-Instruct-2507)
  --steps     Max training steps (default: 500)
  --batch     Rollouts per global batch (default: 512)
              Must be divisible by rollouts_per_example.
  --rollouts  Rollouts per example / GRPO group size (default: 16)
              Larger = more stable gradients, more VRAM. Range: 8-32.
  --tokens    Max completion tokens per rollout (default: 512)
  --wandb     WandB project name (default: prime-lab-<env-name>)
  --config    Output path for TOML (default: configs/rl/<env-name>.toml)
  --yes, -y   Skip confirmation and submit immediately

Defaults match Prime Intellect's documented stable training recipe:
  batch_size=512, rollouts_per_example=16, max_tokens=512
  Reference: https://docs.primeintellect.ai/verifiers/training#configuration

Supported models for Hosted Training:
  Qwen/Qwen3-4B-Instruct-2507      Qwen/Qwen3-4B-Thinking-2507
  Qwen/Qwen3-30B-Instruct-2507     Qwen/Qwen3-30B-Thinking-2507
  Qwen/Qwen3-235B-Instruct-2507    Qwen/Qwen3-235B-Thinking-2507
  PrimeIntellect/INTELLECT-3
"""

import sys
import subprocess
import argparse
from pathlib import Path

SUPPORTED_MODELS = [
    "Qwen/Qwen3-4B-Instruct-2507",
    "Qwen/Qwen3-4B-Thinking-2507",
    "Qwen/Qwen3-30B-Instruct-2507",
    "Qwen/Qwen3-30B-Thinking-2507",
    "Qwen/Qwen3-235B-Instruct-2507",
    "Qwen/Qwen3-235B-Thinking-2507",
    "PrimeIntellect/INTELLECT-3",
]


def check_env_exists(env_id: str):
    """Returns True if found, False if not found, None if CLI unavailable."""
    try:
        result = subprocess.run(
            ["prime", "env", "info", env_id],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode == 0
    except (subprocess.SubprocessError, FileNotFoundError):
        return None


def generate_toml(
    env_id: str,
    model: str,
    steps: int,
    batch_size: int,
    rollouts_per_example: int,
    max_tokens: int,
    wandb_project: str,
    run_name: str,
) -> str:
    """
    Generates a Hosted Training TOML config.

    Format matches the official Prime Intellect documentation exactly:
    https://docs.primeintellect.ai/verifiers/training#configuration

    Canonical example from docs:
        model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
        max_steps = 500
        batch_size = 256
        rollouts_per_example = 8

        [sampling]
        max_tokens = 512

        [[env]]
        id = "primeintellect/alphabet-sort"
        args = { min_turns = 3, max_turns = 5, power_per_turn = false }

        [wandb]
        project = "alphabet-sort"
        name = "qwen3-30b-i-alphabet-sort"

    Note: `args` under [[env]] is omitted here — add manually if your
    environment's load_environment() accepts custom arguments.
    GPU allocation is managed by the Hosted Training platform, not this config.
    """
    return (
        f"# Auto-generated by submit_training.py\n"
        f"# Docs: https://docs.primeintellect.ai/verifiers/training#configuration\n"
        f"# To resubmit: prime rl run <this file>\n"
        f"\n"
        f'model = "{model}"\n'
        f"max_steps = {steps}\n"
        f"batch_size = {batch_size}\n"
        f"rollouts_per_example = {rollouts_per_example}\n"
        f"\n"
        f"[sampling]\n"
        f"max_tokens = {max_tokens}\n"
        f"\n"
        f"[[env]]\n"
        f'id = "{env_id}"\n'
        f"# If your environment accepts args, add them here:\n"
        f"# args = {{ split = \"train\" }}\n"
        f"\n"
        f"# [wandb]  # Uncomment and set WANDB_API_KEY to enable W&B logging\n"
        f'# project = "{wandb_project}"\n'
        f'# name = "{run_name}"\n'
        f"# To submit with W&B: prime rl run <config.toml> -e WANDB_API_KEY=your-key\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--env", required=True, help="Hub environment ID (owner/env-name)")
    parser.add_argument("--model", default="Qwen/Qwen3-4B-Instruct-2507")
    parser.add_argument("--steps", type=int, default=500)
    parser.add_argument("--batch", type=int, default=512,
                        help="Rollouts per global batch. Must be divisible by rollouts_per_example.")
    parser.add_argument("--rollouts", type=int, default=16,
                        help="Rollouts per example (GRPO group size). Range: 8-32.")
    parser.add_argument("--tokens", type=int, default=512,
                        help="Max completion tokens per rollout.")
    parser.add_argument("--wandb", default=None)
    parser.add_argument("--config", default=None)
    parser.add_argument("--yes", "-y", action="store_true")
    args = parser.parse_args()

    env_id = args.env
    env_name = env_id.split("/")[-1]

    print(f"\n{'='*60}")
    print("PRIME LAB TRAINING SUBMISSION")
    print(f"{'='*60}\n")

    # Validate env ID format
    if "/" not in env_id:
        print(f"ERROR: env must be 'owner/env-name', got: '{env_id}'")
        sys.exit(1)

    # Validate batch divisibility
    if args.batch % args.rollouts != 0:
        suggested = args.rollouts * round(args.batch / args.rollouts)
        print(f"ERROR: batch_size ({args.batch}) must be divisible by rollouts_per_example ({args.rollouts}).")
        print(f"  Suggestion: --batch {suggested}")
        sys.exit(1)

    # Warn if model not in supported list
    if args.model not in SUPPORTED_MODELS:
        print(f"WARNING: '{args.model}' is not in the official Hosted Training model list.")
        print("Supported models:")
        for m in SUPPORTED_MODELS:
            print(f"  {m}")
        print()

    # Check env exists on Hub
    print(f"Checking Hub for: {env_id} ...")
    exists = check_env_exists(env_id)
    if exists is True:
        print(f"  Environment confirmed on Hub.\n")
    elif exists is False:
        print(f"  WARNING: '{env_id}' not found via 'prime env list'.")
        print("  Double-check the env ID — submission may fail.\n")
    else:
        print("  (Could not verify — 'prime' CLI unavailable or not logged in)\n")

    # Derive names
    wandb_project = args.wandb or f"prime-lab-{env_name}"
    run_name = f"{args.model.split('/')[-1].lower()}-{env_name}"
    config_path = Path(args.config) if args.config else Path(f"configs/rl/{env_name}.toml")

    # Generate TOML
    toml_content = generate_toml(
        env_id=env_id,
        model=args.model,
        steps=args.steps,
        batch_size=args.batch,
        rollouts_per_example=args.rollouts,
        max_tokens=args.tokens,
        wandb_project=wandb_project,
        run_name=run_name,
    )

    # Show summary
    print(f"Config path : {config_path}\n")
    print("─" * 50)
    print(toml_content)
    print("─" * 50)
    print(f"Environment : {env_id}")
    print(f"Model       : {args.model}")
    print(f"Steps       : {args.steps}")
    print(f"Batch size  : {args.batch}  ({args.batch // args.rollouts} prompts × {args.rollouts} rollouts)")
    print(f"Rollouts    : {args.rollouts} per example (GRPO group size)")
    print(f"Max tokens  : {args.tokens}")
    print(f"WandB       : {wandb_project} / {run_name}")
    print()

    if not args.yes:
        answer = input("Submit training run? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("Aborted. Config was NOT saved.")
            sys.exit(0)

    # Write config
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(toml_content)
    print(f"\n  Config saved to {config_path}")

    # Submit
    print(f"  Submitting: prime rl run {config_path}\n")
    try:
        subprocess.run(
            ["prime", "rl", "run", str(config_path)],
            check=True,
        )
        print("Training run submitted.")
        print("Monitor : prime rl list")
        print("Logs    : prime rl logs <run-id>")
    except FileNotFoundError:
        print("ERROR: 'prime' CLI not found. Install: pip install prime")
        print(f"Config saved at {config_path}. Run manually:")
        print(f"  prime rl run {config_path}")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: prime rl run exited with code {e.returncode}")
        print(f"Config saved at {config_path}. Debug and retry:")
        print(f"  prime rl run {config_path}")
        sys.exit(1)


if __name__ == "__main__":
    main()